/**
 * Serialises a schema object into a JSON-LD script tag.
 *
 * `<` is escaped so a stray `</script>` inside content (a blog excerpt, a job
 * description) cannot break out of the tag.
 */
export function JsonLd({ schema }: { schema: object | object[] }) {
  const payload = JSON.stringify(schema).replace(/</g, "\\u003c");

  return (
    <script
      type="application/ld+json"
      // The payload is generated by our own schema builders, never user input.
      dangerouslySetInnerHTML={{ __html: payload }}
    />
  );
}
